# Generated by Django 3.1.7 on 2021-03-24 08:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_auto_20210324_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator('^/^[a-zA-Z ]*$/', 'Only alphabet characters and spaces are allowed.')]),
        ),
    ]
