# Generated by Django 3.1.7 on 2021-03-24 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0011_auto_20210324_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.RegexValidator('[a-zA-Z][a-zA-Z ]+', 'Only alphabet characters and spaces are allowed.')]),
        ),
    ]
